# Generated by Django 4.2.17 on 2025-01-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicationPoint',
            fields=[
                ('repository', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('communication_types', models.ManyToManyField(related_name='relying_parties', to='inconsistency.communicationtype')),
            ],
        ),
        migrations.CreateModel(
            name='RelyingParty',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('filters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100)),
                ('asn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unreachability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('error_messages', models.ManyToManyField(related_name='unreachabilities', to='inconsistency.errormessage')),
                ('publication_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unreachabilities', to='inconsistency.publicationpoint')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unreachabilities', to='inconsistency.update')),
            ],
        ),
        migrations.AddField(
            model_name='publicationpoint',
            name='urls',
            field=models.ManyToManyField(related_name='relying_parties', to='inconsistency.url'),
        ),
        migrations.CreateModel(
            name='Inconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_object', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('time_stamp', models.DateTimeField()),
                ('accepting_rps', models.ManyToManyField(related_name='accepting', to='inconsistency.relyingparty')),
                ('affected_vrps', models.ManyToManyField(related_name='inconsistencies', to='inconsistency.vrp')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='inconsistency.owner')),
                ('rejecting_rps', models.ManyToManyField(related_name='rejecting', to='inconsistency.relyingparty')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='inconsistency.update')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('time_stamp', models.DateTimeField()),
                ('affected_vrps', models.ManyToManyField(related_name='errors', to='inconsistency.vrp')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='inconsistency.owner')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='inconsistency.update')),
            ],
        ),
    ]
