/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_rrdpentry_free: (a: number, b: number) => void;
export const rrdpentry_new: (a: number, b: number, c: number, d: number) => number;
export const rrdpentry_uri: (a: number) => [number, number];
export const rrdpentry_content: (a: number) => [number, number];
export const __wbg_state_free: (a: number, b: number) => void;
export const state_new: (a: number, b: number) => [number, number, number];
export const state_drag_node: (a: number, b: number, c: number, d: number) => [number, number];
export const state_repositorify: (a: number) => [number, number];
export const state_load_example: (a: number, b: number) => [number, number, number];
export const state_get_nodes: (a: number) => [number, number];
export const state_add_node: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const state_adapt_node_content: (a: number, b: number, c: number, d: number) => [number, number];
export const state_adapt_node_all: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const state_adapt_node_length: (a: number, b: number, c: number) => [number, number];
export const state_adapt_node_tag: (a: number, b: number, c: number) => [number, number];
export const state_adapt_node_label: (a: number, b: number, c: number, d: number) => [number, number];
export const state_remove_node: (a: number, b: number) => [number, number];
export const state_export_bin: (a: number) => [number, number];
export const state_export_base64: (a: number) => [number, number];
export const state_encode_store: (a: number) => [number, number];
export const state_from_stored: (a: number, b: number) => [number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
